class MoroccanCities {
  static const Map<String, String> cities = {
    "agadir": "Agadir",
    "alHoceima": "Al Hoceima",
    "azilal": "Azilal",
    "beniMellal": "Béni Mellal",
    "benslimane": "Benslimane",
    "berkane": "Berkane",
    "berrechid": "Berrechid",
    "boujdour": "Boujdour",
    "boulemane": "Boulemane",
    "casablanca": "Casablanca",
    "chefchaouen": "Chefchaouen",
    "chichaoua": "Chichaoua",
    "dakhla": "Dakhla",
    "elJadida": "El Jadida",
    "errachidia": "Errachidia",
    "essaouira": "Essaouira",
    "fes": "Fès",
    "figuig": "Figuig",
    "guelmim": "Guelmim",
    "guercif": "Guercif",
    "ifaWadane": "Ifa Wadane",
    "ifrane": "Ifrane",
    "inezgane": "Inzegane",
    "kenitra": "Kénitra",
    "khenifra": "Khénifra",
    "khouribga": "Khouribga",
    "ksarElKebir": "Ksar El Kebir",
    "laayoune": "Laâyoune",
    "larache": "Larache",
    "marrakech": "Marrakech",
    "meknes": "Meknès",
    "midelt": "Midelt",
    "nador": "Nador",
    "ouarzazate": "Ouarzazate",
    "oujda": "Oujda",
    "rabat": "Rabat",
    "safi": "Safi",
    "sale": "Salé",
    "sebtGzoula": "Sebt Gzoula",
    "settat": "Settat",
    "sidiIfni": "Sidi Ifni",
    "sidiKacem": "Sidi Kacem",
    "sidiSlimane": "Sidi Slimane",
    "tanTan": "Tan-Tan",
    "tanger": "Tanger",
    "taounate": "Taounate",
    "taourirt": "Taourirt",
    "tarfaya": "Tarfaya",
    "taroudant": "Taroudant",
    "tata": "Tata",
    "tetouan": "Tétouan",
    "tinghir": "Tinghir",
    "tiznit": "Tiznit",
    "zagora": "Zagora",
    "akka": "Akka",
    "boudnib": "Boudnib",
    "bouarfa": "Bouarfa",
    "benJadid": "Ben Jadid",
    "bhalil": "Bhalil",
    "bojador": "Bojador",
    "kelaatMgouna": "Kelaât Mgouna",
    "mehdiya": "Mehdiya",
    "moulayIdriss": "Moulay Idriss",
    "meskala": "Meskala",
    "moulayYacoub": "Moulay Yacoub",
    "nouaceur": "Nouaceur",
    "ouledZiane": "Ouled Ziane",
    "ouladGhanem": "Oulad Ghanem",
    "rissani": "Rissani",
    "sidiBouzid": "Sidi Bouzid",
    "tounfite": "Tounfite",
    "temara": "Temara",
    "mohammedia": "Mohammedia",
    "taza": "Taza",
    "aitMelloul": "Ait Melloul",
    "ouazzane": "Ouazzane",
    "fnideq": "Fnideq",
    "soukLarbaa": "Souk Larbaa",
    "khemisset": "Khemisset",
    "smara": "Smara",
    "kelaaDesSraghna": "El Kelaa des Sraghna"
  };
}
