name: luxora_cosmetics_frontend
description: 'An E-commerce project made by Ali Salem Essouiah Custom Flutter System.'
publish_to: 'none'
version: 1.0.0
license: All Rights Reserved

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  # collections
  collection: ^1.18.0
  # Navigation and routing management
  beamer: ^1.6.2
  # Checks network connectivity status
  connectivity_plus: ^6.0.5
  # Networking client for HTTP requests
  dio: ^5.7.0
  # Simplifies equality comparisons
  equatable: ^2.0.5
  # Enables complex animations
  flutter_animate: ^4.5.0
  # State management using the Bloc pattern
  flutter_bloc: ^8.1.6
  # React hooks-style functions for Flutter
  flutter_hooks: ^0.20.5
  # Localization support for Flutter
  flutter_localization: ^0.2.2
  # Automatically generates native splash screens
  flutter_native_splash: ^2.4.1
  # Supports SVG rendering
  flutter_svg: ^2.0.10+1
  # Dependency injection service locator
  get_it: ^8.0.0
  # Date and number formatting
  intl: ^0.19.0
  # JSON serialization support
  json_annotation: ^4.9.0
  # Logging utility for debugging
  logger: ^2.4.0
  # HTTP API client generator using annotations
  retrofit: ^4.4.1
  # Local storage for simple key-value pairs
  shared_preferences: ^2.3.2
  # Opens URLs in external applications
  url_launcher: ^6.3.0
  # Data visualization library for charts
  fl_chart: ^0.69.0
  # Circular percentage indicators
  percent_indicator: ^4.2.3
  # Lottie animations for Flutter
  lottie: ^3.1.2
  # Carousel slider for images or widgets
  carousel_slider: ^5.0.0
  # Integrates Google Maps
  uuid: ^4.5.1
  #syncFusion calendar
  syncfusion_flutter_datepicker: ^28.2.4
  webview_flutter: ^4.10.0

  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting rules and recommendations
  flutter_lints: ^3.0.0
  # Generates code from annotations (e.g., for JSON serialization)
  build_runner: ^2.4.9
  # Generates app launcher icons
  flutter_launcher_icons: ^0.13.1
  # Code generator for JSON serialization
  json_serializable: ^6.7.1
  # Code generator for Retrofit
  retrofit_generator: '>=7.0.0 <8.0.0'

flutter:
  assets:
    - assets/files/
    - assets/files/lottie/
    - assets/vectors/
    - assets/images/
    - assets/animated_images/
    - assets/icons/
    - assets/translations/
  fonts:
    - family: recoleta
      fonts:
        - asset: assets/fonts/recoleta/recoleta-thin.otf
          weight: 100
        - asset: assets/fonts/recoleta/recoleta-light.otf
          weight: 300
        - asset: assets/fonts/recoleta/recoleta-regular.otf
          weight: 400
        - asset: assets/fonts/recoleta/recoleta-medium.otf
          weight: 500
        - asset: assets/fonts/recoleta/recoleta-semibold.otf
          weight: 600
        - asset: assets/fonts/recoleta/recoleta-bold.otf
          weight: 700
        - asset: assets/fonts/recoleta/recoleta-black.otf
          weight: 900
    - family: recoleta-alt
      fonts:
        - asset: assets/fonts/recoleta_alt/recoleta-alt-thin.otf
          weight: 100
        - asset: assets/fonts/recoleta_alt/recoleta-alt-light.otf
          weight: 300
        - asset: assets/fonts/recoleta_alt/recoleta-alt-regular.otf
          weight: 400
        - asset: assets/fonts/recoleta_alt/recoleta-alt-medium.otf
          weight: 500
        - asset: assets/fonts/recoleta_alt/recoleta-alt-semibold.otf
          weight: 600
        - asset: assets/fonts/recoleta_alt/recoleta-alt-bold.otf
          weight: 700
        - asset: assets/fonts/recoleta_alt/recoleta-alt-black.otf
          weight: 900
    - family: inter
      fonts:
        - asset: assets/fonts/inter/inter-thin.ttf
          weight: 100
        - asset: assets/fonts/inter/inter-thinitalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/inter/inter-extralight.ttf
          weight: 200
        - asset: assets/fonts/inter/inter-extralightitalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/inter/inter-light.ttf
          weight: 300
        - asset: assets/fonts/inter/inter-lightitalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/inter/inter-regular.ttf
          weight: 400
        - asset: assets/fonts/inter/inter-medium.ttf
          weight: 500
        - asset: assets/fonts/inter/inter-mediumitalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/inter/inter-semibold.ttf
          weight: 600
        - asset: assets/fonts/inter/inter-semibolditalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/inter/inter-bold.ttf
          weight: 700
        - asset: assets/fonts/inter/inter-bolditalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/inter/inter-extrabold.ttf
          weight: 800
        - asset: assets/fonts/inter/inter-extrabolditalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/inter/inter-black.ttf
          weight: 900
        - asset: assets/fonts/inter/inter-blackitalic.ttf
          weight: 900
          style: italic

  uses-material-design: true
