name: luxora_cosmetics_frontend
description: 'An E-commerce project made by Ali Salem Essouiah Custom Flutter System.'
publish_to: 'none'
version: 1.0.0
license: All Rights Reserved

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.1
  beamer: ^1.7.0
  connectivity_plus: ^6.1.3
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.0
  flutter_native_splash: ^2.4.5
  flutter_svg: ^2.0.17
  get_it: ^8.0.3
  json_annotation: ^4.9.0
  logger: ^2.5.0
  retrofit: ^4.4.2
  shared_preferences: ^2.5.2
  url_launcher: ^6.3.1
  percent_indicator: ^4.2.4
  lottie: ^3.3.1
  carousel_slider: ^5.0.0
  uuid: ^4.5.1
  syncfusion_flutter_datepicker: ^28.2.11
  webview_flutter: ^4.10.0
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  retrofit_generator: ^9.1.9

flutter:
  assets:
    - assets/files/
    - assets/files/lottie/
    - assets/vectors/
    - assets/images/
    - assets/animated_images/
    - assets/icons/
    - assets/translations/
  fonts:
    - family: recoleta
      fonts:
        - asset: assets/fonts/recoleta/recoleta-thin.otf
          weight: 100
        - asset: assets/fonts/recoleta/recoleta-light.otf
          weight: 300
        - asset: assets/fonts/recoleta/recoleta-regular.otf
          weight: 400
        - asset: assets/fonts/recoleta/recoleta-medium.otf
          weight: 500
        - asset: assets/fonts/recoleta/recoleta-semibold.otf
          weight: 600
        - asset: assets/fonts/recoleta/recoleta-bold.otf
          weight: 700
        - asset: assets/fonts/recoleta/recoleta-black.otf
          weight: 900
    - family: recoleta-alt
      fonts:
        - asset: assets/fonts/recoleta_alt/recoleta-alt-thin.otf
          weight: 100
        - asset: assets/fonts/recoleta_alt/recoleta-alt-light.otf
          weight: 300
        - asset: assets/fonts/recoleta_alt/recoleta-alt-regular.otf
          weight: 400
        - asset: assets/fonts/recoleta_alt/recoleta-alt-medium.otf
          weight: 500
        - asset: assets/fonts/recoleta_alt/recoleta-alt-semibold.otf
          weight: 600
        - asset: assets/fonts/recoleta_alt/recoleta-alt-bold.otf
          weight: 700
        - asset: assets/fonts/recoleta_alt/recoleta-alt-black.otf
          weight: 900
    - family: inter
      fonts:
        - asset: assets/fonts/inter/inter-thin.ttf
          weight: 100
        - asset: assets/fonts/inter/inter-thinitalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/inter/inter-extralight.ttf
          weight: 200
        - asset: assets/fonts/inter/inter-extralightitalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/inter/inter-light.ttf
          weight: 300
        - asset: assets/fonts/inter/inter-lightitalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/inter/inter-regular.ttf
          weight: 400
        - asset: assets/fonts/inter/inter-medium.ttf
          weight: 500
        - asset: assets/fonts/inter/inter-mediumitalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/inter/inter-semibold.ttf
          weight: 600
        - asset: assets/fonts/inter/inter-semibolditalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/inter/inter-bold.ttf
          weight: 700
        - asset: assets/fonts/inter/inter-bolditalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/inter/inter-extrabold.ttf
          weight: 800
        - asset: assets/fonts/inter/inter-extrabolditalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/inter/inter-black.ttf
          weight: 900
        - asset: assets/fonts/inter/inter-blackitalic.ttf
          weight: 900
          style: italic

  uses-material-design: true